# Generated by Django 2.1.15 on 2020-03-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('actor_id', models.CharField(default='00000', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='演员名字')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, verbose_name='性别')),
                ('birth', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=225, null=True, verbose_name='出生地')),
                ('graduation', models.CharField(blank=True, max_length=225, null=True, verbose_name='毕业学校')),
                ('image', models.ImageField(upload_to='icon/%Y%m%d', verbose_name='头像')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'admin_info',
            },
        ),
        migrations.CreateModel(
            name='auteur',
            fields=[
                ('auteur_id', models.CharField(default='00000', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225, verbose_name='导演名称')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '男')], default=2)),
                ('birth', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=225, null=True, verbose_name='出生地')),
                ('graduation', models.CharField(blank=True, max_length=225, null=True, verbose_name='毕业学校')),
                ('image', models.ImageField(upload_to='icon/%Y%m%d', verbose_name='头像')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auteur',
            },
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.CharField(default='00000', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='电影名称')),
                ('movie_desc', models.TextField(verbose_name='简介')),
                ('movie_image', models.ImageField(upload_to='movie/%Y%m%d', verbose_name='电影宣传页')),
                ('movie_country', models.CharField(blank=True, max_length=225, null=True, verbose_name='电影拍摄国家')),
                ('movie_run', models.CharField(blank=True, max_length=225, null=True, verbose_name='电影上映时间')),
                ('movie_score', models.FloatField(default='0.0', verbose_name='电影评分')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('movie_actor', models.ManyToManyField(related_name='movie_actor', to='administrator.actor')),
                ('movie_auteur', models.ManyToManyField(related_name='movie_auteur', to='administrator.auteur')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='movie_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='电影类型编号')),
                ('name', models.CharField(max_length=50, verbose_name='电影类型')),
            ],
            options={
                'db_table': 'movie_type',
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('movies_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.movie')),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.AddField(
            model_name='score',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.user_info'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.ManyToManyField(to='administrator.movie_type'),
        ),
    ]
