# Generated by Django 2.1.15 on 2020-03-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='movies_id',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='users_id',
            new_name='user_id',
        ),
    ]
